# word_bank.py
# Action verbs organized by skill category

ACTION_VERBS = {
    "Leadership": [
        "Coordinated", "Directed", "Facilitated", "Guided", 
        "Led", "Managed", "Mentored", "Supervised", "Organized",
        "Spearheaded", "Championed", "Orchestrated"
    ],
    "Communication": [
        "Advised", "Collaborated", "Consulted", "Presented",
        "Communicated with", "Engaged", "Counseled", "Instructed",
        "Liaised with", "Briefed", "Informed"
    ],
    "Problem-Solving": [
        "Analyzed", "Assessed", "Developed", "Implemented",
        "Improved", "Resolved", "Streamlined", "Designed",
        "Optimized", "Troubleshot", "Innovated"
    ],
    "Teamwork": [
        "Assisted", "Contributed to", "Partnered with", 
        "Supported", "Cooperated with", "Helped", "Aided",
        "Collaborated on", "Participated in"
    ]
}

# Skill keywords for different roles (6 keywords each for variety)
SKILL_KEYWORDS = {
    "tutor": ["curriculum development", "student assessment", "personalized learning strategies", "academic progress tracking", "educational support", "learning outcome improvement"],
    "student mentor": ["peer counseling", "academic advising", "student engagement", "goal setting", "retention initiatives", "success planning"],
    "mentor": ["professional development", "career guidance", "skill building", "performance coaching", "growth strategies", "talent development"],
    "volunteer": ["community outreach", "event coordination", "public relations", "social impact", "nonprofit operations", "civic engagement"],
    "caregiver": ["patient care", "daily living assistance", "health monitoring", "compassionate support", "medical coordination", "wellness promotion"],
    "babysitter": ["child supervision", "age-appropriate activities", "safety protocols", "behavioral management", "developmental activities", "family communication"],
    "coach": ["team building", "performance evaluation", "training programs", "motivational leadership", "skills development", "competitive strategy"],
    "cashier": ["customer service", "point-of-sale systems", "cash handling", "inventory management", "transaction accuracy", "customer satisfaction"],
    "server": ["customer satisfaction", "order accuracy", "time management", "hospitality services", "dining experience enhancement", "team coordination"],
    "intern": ["project collaboration", "research analysis", "professional communication", "industry best practices", "cross-functional support", "organizational learning"],
    "teacher": ["lesson planning", "classroom management", "educational technology", "student development", "curriculum implementation", "assessment strategies"],
    "receptionist": ["front desk operations", "scheduling", "phone etiquette", "administrative support", "visitor management", "office coordination"],
    "sales associate": ["product knowledge", "sales targets", "customer relations", "merchandising", "inventory control", "revenue generation"],
    "camp counselor": ["youth development", "activity planning", "conflict resolution", "safety supervision", "group facilitation", "recreational programming"],
    "research assistant": ["data collection", "literature review", "statistical analysis", "research methodology", "documentation", "laboratory protocols"],
    "lifeguard": ["water safety", "emergency response", "CPR certification", "surveillance protocols", "rescue operations", "safety enforcement"],
    "barista": ["beverage preparation", "customer engagement", "inventory control", "food safety", "quality standards", "workflow efficiency"],
    "retail worker": ["visual merchandising", "stock management", "sales techniques", "brand representation", "customer service", "store operations"],
    "lab assistant": ["laboratory procedures", "equipment maintenance", "data recording", "safety compliance", "sample processing", "quality control"],
    "event coordinator": ["logistics planning", "vendor management", "budget oversight", "stakeholder communication", "timeline coordination", "event execution"],
    "office assistant": ["administrative tasks", "document organization", "scheduling coordination", "office supply management", "communication facilitation", "clerical support"],
    "warehouse worker": ["inventory management", "shipping and receiving", "safety protocols", "equipment operation", "order fulfillment", "stock organization"],
    "delivery driver": ["route optimization", "customer service", "time management", "vehicle maintenance", "safety compliance", "package handling"],
    "food service worker": ["food preparation", "sanitation standards", "customer service", "order accuracy", "kitchen operations", "team collaboration"],
    "nursing assistant": ["patient care", "vital signs monitoring", "medical documentation", "patient comfort", "clinical support", "healthcare teamwork"],
    "teacher's aide": ["classroom support", "student assistance", "instructional materials", "behavior management", "educational activities", "progress monitoring"],
    "library assistant": ["catalog management", "customer service", "resource organization", "research support", "technology assistance", "collection maintenance"],
    "gym attendant": ["equipment maintenance", "facility cleanliness", "member assistance", "safety monitoring", "customer service", "operational support"],
    "dog walker": ["pet care", "exercise routines", "safety protocols", "client communication", "scheduling management", "animal behavior observation"],
    "house cleaner": ["sanitation procedures", "time management", "attention to detail", "client satisfaction", "cleaning techniques", "supply management"],
    "landscaper": ["grounds maintenance", "equipment operation", "plant care", "design implementation", "safety practices", "seasonal upkeep"],
    "park ranger": ["visitor services", "environmental education", "safety enforcement", "resource conservation", "public outreach", "wildlife management"],
    "museum guide": ["public speaking", "historical knowledge", "tour facilitation", "visitor engagement", "educational programming", "cultural interpretation"],
    "pharmacy technician": ["prescription processing", "inventory management", "customer service", "medication verification", "regulatory compliance", "insurance coordination"],
    "dental assistant": ["patient care", "clinical support", "sterilization procedures", "appointment coordination", "dental procedures assistance", "record keeping"],
    "veterinary assistant": ["animal care", "client communication", "medical equipment preparation", "patient monitoring", "administrative tasks", "clinic operations"],
    "graphic designer": ["visual communication", "creative development", "client collaboration", "brand consistency", "design software proficiency", "project management"],
    "social media coordinator": ["content creation", "community engagement", "analytics tracking", "brand voice development", "platform management", "marketing strategy"],
    "data entry clerk": ["accuracy verification", "database management", "typing proficiency", "data organization", "quality control", "workflow efficiency"],
    "customer service representative": ["issue resolution", "customer satisfaction", "product knowledge", "communication skills", "conflict management", "service standards"],
    "administrative assistant": ["office coordination", "calendar management", "correspondence handling", "meeting preparation", "document processing", "executive support"],
    "project coordinator": ["task management", "deadline tracking", "team communication", "resource allocation", "progress monitoring", "stakeholder updates"],
    "sales manager": ["team leadership", "revenue growth", "sales strategy", "performance coaching", "client relationships", "market analysis"],
    "store manager": ["operations oversight", "staff development", "inventory control", "financial management", "customer experience", "strategic planning"],
    "assistant manager": ["operational support", "team supervision", "problem resolution", "scheduling coordination", "quality assurance", "performance improvement"],
    "shift supervisor": ["team coordination", "workflow management", "quality control", "staff training", "operational efficiency", "shift reporting"],
    "hotel front desk": ["guest relations", "reservation management", "check-in procedures", "customer service excellence", "problem resolution", "hospitality standards"],
    "front desk": ["visitor reception", "appointment scheduling", "phone management", "customer service", "administrative coordination", "professional communication"]
}

# Experience mappings for natural resume language
EXPERIENCE_MAPPINGS = {
    "tutor": "students across various academic subjects",
    "student mentor": "peers navigating academic and personal challenges",
    "mentor": "individuals seeking professional and personal growth",
    "volunteer": "community organizations and local initiatives",
    "caregiver": "individuals requiring daily assistance and health monitoring",
    "babysitter": "children in safe, engaging, and developmentally appropriate environments",
    "coach": "athletes and team members to reach performance goals",
    "cashier": "customers through efficient and accurate transactions",
    "server": "restaurant guests with exceptional dining experiences",
    "intern": "organizational teams on key projects and daily operations",
    "teacher": "students in comprehensive learning experiences",
    "receptionist": "office visitors and internal staff with professionalism",
    "sales associate": "customers in product selection and purchasing decisions",
    "camp counselor": "youth in recreational, educational, and social activities",
    "research assistant": "faculty and research teams in academic investigations",
    "lifeguard": "swimmers and pool patrons ensuring aquatic safety",
    "barista": "customers with quality beverages and friendly service",
    "retail worker": "store operations and customer shopping experiences",
    "lab assistant": "scientific research teams with laboratory procedures",
    "event coordinator": "events from initial planning through successful execution",
    "office assistant": "office staff with administrative and organizational tasks",
    "warehouse worker": "supply chain operations and inventory systems",
    "delivery driver": "timely and accurate package delivery to customers",
    "food service worker": "food preparation and customer service in dining environments",
    "nursing assistant": "patients with compassionate care and medical support",
    "teacher's aide": "classroom instruction and individual student needs",
    "library assistant": "library patrons with research and resource access",
    "gym attendant": "fitness facility members and equipment maintenance",
    "dog walker": "pets with exercise, care, and outdoor activities",
    "house cleaner": "residential clients with thorough cleaning services",
    "landscaper": "property maintenance and outdoor aesthetic improvements",
    "park ranger": "park visitors while protecting natural resources",
    "museum guide": "museum visitors through educational and engaging tours",
    "pharmacy technician": "pharmacy operations and patient medication needs",
    "dental assistant": "dental procedures and patient comfort",
    "veterinary assistant": "veterinary care and animal welfare",
    "graphic designer": "visual design projects and brand communications",
    "social media coordinator": "digital engagement and online community building",
    "data entry clerk": "accurate data processing and database management",
    "customer service representative": "customer inquiries and service needs",
    "administrative assistant": "executive and office administrative functions",
    "project coordinator": "project timelines and cross-functional team collaboration",
    "sales manager": "sales team performance and revenue objectives",
    "store manager": "retail operations and team productivity",
    "assistant manager": "daily operations and staff coordination",
    "shift supervisor": "team performance during assigned shifts",
    "hotel front desk": "guest experiences and hotel operations",
    "front desk": "reception operations and visitor services"
}